# TODO:
# how to prevent the loss of the html css styling upon conversion from html to epub via pandoc?
# -> use calibre instead of pandoc
# see https://github.com/rjl20/hpmor/blob/master/ebook/2_html2epub.sh


# requirements
# Linux
# sudo apt-get install pandoc calibre

# MacOS
# brew install pandoc
# brew install calibre

# required for pdf
# sudo apt install texlive texlive-latex-base texlive-base texlive-lang-german texlive-latex-extra

# source is html file generated by hpmor_1b_extract_and_convert.py

# V1: single threading
# for LANG in en de en2; 
for LANG in en de; 
  do 
  echo === $LANG ===
    # epub
    echo html to markdown
    pandoc -o output/hpmor-$LANG.md    output/hpmor-$LANG.html
    echo markdown to epub
    pandoc -o output/hpmor-$LANG.epub  meta4pandoc/meta-$LANG.md   output/hpmor-$LANG.md
    echo epub to mobi
    pandoc -o output/hpmor-$LANG.mobi  output/hpmor-$LANG.epub
    # markdown for simply modification
    # echo epub to pdf
    # pandoc -o output/hpmor-$LANG.pdf   output/hpmor-$LANG.epub
  done

# V2: multi threading
# echo === html to markdown ===
# #for LANG in en de en2; 
# for LANG in en de; 
#   do 
#   pandoc -o output/hpmor-$LANG.md    output/hpmor-$LANG.html &
# done
# for LANG in en2; 
#   pandoc -o output/hpmor-$LANG.md --css output/hpmor-$LANG.css   output/hpmor-$LANG.html &
# done
# wait

# echo === markdown to epub ===
# #for LANG in en de en2; 
# for LANG in en2; 
#   do 
#     pandoc -o output/hpmor-$LANG.epub  images/title-$LANG.md   output/hpmor-$LANG.md &
# done
# wait
 
# echo === epub to mobi ===
# for LANG in en de en2; 
# #for LANG in en2; 
#   do 
#     # mobi via calibre on Mac
#     /Applications/calibre.app/Contents/MacOS/ebook-convert output/hpmor-$LANG.epub output/hpmor-$LANG.mobi &
#     # pandoc -o output/hpmor-$LANG.mobi  output/hpmor-$LANG.epub &
#     # pdf did not work from html, so started from epub instead
#     pandoc -o output/hpmor-$LANG.pdf   output/hpmor-$LANG.epub &
#   done
# wait

# echo === epub to PDF ===
# for LANG in en de en2; 
# #for LANG in en2; 
#   do 
#     # pdf did not work from html, so started from epub instead
#     pandoc -o output/hpmor-$LANG.pdf   output/hpmor-$LANG.epub &
#   done
# wait


# upload to entorb.net/hpmor
# rsync -rvhu --delete --delete-excluded --no-perms output/hpmor-* entorb@entorb.net:html/hpmor/
